'use strict'

// Action constants
export const ACTION_LOAD_START = 'ACTION_LOAD_START';
export const ACTION_LOAD_END = 'ACTION_LOAD_END';
export const ACTION_LOAD_PROGRESS = 'ACTION_LOAD_PROGRESS';

export const ACTION_COMMAND_INPUT = 'ACTION_COMMAND_INPUT';
export const ACTION_COMMAND_SELECT = 'ACTION_COMMAND_SELECT';
export const ACTION_COMMAND_SHOW = 'ACTION_COMMAND_SHOW';

export const MODE_NAVIGATION = 'MODE_NAVIGATION';
export const MODE_COMMAND = 'MODE_COMMAND';

export const HEIGHT_CC_NAVIGATION = 30;
export const HEIGHT_CC_COMMAND = 44;

export const RESULT_TYPE_URL = 'RESULT_TYPE_URL';
export const RESULT_TYPE_HISTORY = 'RESULT_TYPE_HISTORY';
export const RESULT_TYPE_SEARCH = 'RESULT_TYPE_SEARCH';
export const RESULT_TYPE_PIN = 'RESULT_TYPE_PIN';
