'use strict'

// Action constants
export const ACTION_NAVIGATION_STATE = 'ACTION_NAVIGATION_STATE';
export const ACTION_COMMAND_INPUT = 'ACTION_COMMAND_INPUT';
export const ACTION_COMMAND_SELECT = 'ACTION_COMMAND_SELECT';
export const ACTION_COMMAND_SHOW = 'ACTION_COMMAND_SHOW';
export const ACTION_SEARCH_RESULTS = 'ACTION_SEARCH_RESULTS';

export const MODE_NAVIGATION = 'MODE_NAVIGATION';
export const MODE_COMMAND = 'MODE_COMMAND';

export const HEIGHT_CC_NAVIGATION = 30;
export const HEIGHT_CC_COMMAND = 44;
